In [ ]:
import numpy as np


In [ ]:
b = np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
c = np.ones(10)
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
mylist = [5,5,5,5,5,5,5,5,5,5]
d = np.array(mylist)
print(d)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
e = np.arange (10,51)
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
f = np.arange (10,51,2)
print(f)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
g_list = [[0,1,2],[3,4,5],[6,7,8]]
g = np.array(g_list)
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

i = np.random.random()
print(i)

0.3875378119043126


In [ ]:
j = np.random.randn(25)
print(j)

[-0.54226306 -0.37064511  0.39855335 -0.33197921 -1.33306519  0.61767368
  0.87345271 -1.72547243 -0.67905609 -0.28525173  1.35267567 -1.68077856
  0.27576247 -0.63956646 -1.93267245 -1.12477893  2.13252083 -2.38510215
  0.23742693  0.42102362 -0.43094652  0.09139896 -1.34377034 -0.81564114
  0.37023503]


In [ ]:
k = np.arange(0.01,1.01,0.01)
print(k)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


In [15]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
l = mat[2:,1:]
print(l)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [20]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
m = mat[3,4]
print(m)

20


In [19]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
n = mat[0:3,1]
n1 = np.array(i)
print(n1)

[ 2  7 12]


In [21]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
o = mat[4,:]
print(o)

[21 22 23 24 25]


In [24]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
p = mat[3:,:]
print(p)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [27]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [1]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat.sum(axis=0))

[55 60 65 70 75]
